[package]
name = "ghost"
version = "0.1.0"
authors = ["Nathan Nguyen <nathan.tm.nguyen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "0.17.1"
itertools = "0.9.0"
